sudo: required

language: php

services:
  - docker

script:
  - docker version
  - docker build -t zaporylie/drupal-dev .
  - docker ps -a
  - docker run --name drupal-dev -ti zaporylie/drupal-dev /root/conf/test.sh
