sudo: required

services:
  - docker

env:
  global:
    - APP_IMAGE_NAME=zaporylie/drupal-dev
    - APP_CONTAINER_NAME=drupal
    - DB_CONTAINER_NAME=mysql
    - DB_HOSTNAME=db
    - DB_VERSION=5.5
    - CODE_SYNC_METHOD=auto
    - CODE_DRUSH_MAJOR_VERSION=8
    - DRUPAL_PROFILE=minimal
    - DRUPAL_SUBDIR=default
    - DB_SYNC_METHOD=auto
    - CODE_GIT_CLONE_BRANCH=8.0.x
  matrix:
    # Try local database.
    - DB_HOSTNAME=
    # Try different version of mysql.
    - DB_VERSION=5.6
    # Try clone git repo.
    - CODE_SYNC_METHOD=git
    # Try clone drupal git repo with given branch.
    - CODE_SYNC_METHOD=git CODE_GIT_CLONE_BRANCH=7.x
    # Try Drupal 7 with Drush.
    - CODE_SYNC_METHOD=drush CODE_DRUSH_MAJOR_VERSION=7
    # Different instalation profile.
    - DRUPAL_PROFILE=standard
    # Different subdir
    - DRUPAL_SUBDIR=localhost

script:
  # Show version of Docker used to build image and run container.
  - docker version
  # Build image (use the same namespace as on docker hub)
  - docker build -t ${APP_IMAGE_NAME} .
  # Run mysql container.
  - docker run -d --name ${DB_CONTAINER_NAME} -e MYSQL_ROOT_PASSWORD=test mysql:${DB_VERSION}
  # Show all docker images.
  - docker images
  # Show all container.
  - docker ps -a
  # Run container in test mode.
  - docker run -i --name ${APP_CONTAINER_NAME} --link ${DB_CONTAINER_NAME}:db -e DB_HOSTNAME=${DB_HOSTNAME} -e CODE_SYNC_METHOD=${CODE_SYNC_METHOD} -e CODE_DRUSH_MAJOR_VERSION=${CODE_DRUSH_MAJOR_VERSION} -e CODE_GIT_CLONE_BRANCH=${CODE_GIT_CLONE_BRANCH} -e DRUPAL_SUBDIR=${DRUPAL_SUBDIR} -e DRUPAL_PROFILE=${DRUPAL_PROFILE} -e TEST_BUILD=true ${APP_IMAGE_NAME}